export const PokemonTypes = [
    { name: 'normal',   color: 'gray' },
    { name: 'fighting', color: 'yellow' },
    { name: 'flying',   color: 'blue' },
    { name: 'poison',   color: 'purple' },
    { name: 'ground',   color: 'orange' },
    { name: 'rock',     color: 'gray' },
    { name: 'bug',      color: 'green' },
    { name: 'ghost',    color: 'gray' },
    { name: 'steel',    color: 'gray' },
    { name: 'fire',     color: 'red' },
    { name: 'water',    color: 'cyan' },
    { name: 'grass',    color: 'green' },
    { name: 'electric', color: 'yellow' },
    { name: 'psychic',  color: 'pink' },
    { name: 'ice',      color: 'cyan' },
    { name: 'dragon',   color: 'red' },
    { name: 'dark',     color: 'gray' },
    { name: 'fairy',    color: 'pink' },
    { name: 'unknown',  color: 'orange' },
    { name: 'shadow',   color: 'gray' },
]